remote_theme: "mmistakes/minimal-mistakes"
 plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
 title: "Site Title"
 description: "An amazing website."

 # Site Author
author:
  name             : "Teresia Kemunto Omae"
  #avatar           : "Teresia_Kemunto_Photo.jpeg"
  bio              : "I am passionate about Cloud and Network Security."
  location         : "Nairobi, Kenya"
  email            : "teresiakemunto8@gmail.com
  # fediverse      : "@you@instance.social"  # used for fediverse:creator meta tag
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "teresiakemunto8@gmail.com"
    #- label: "Website"
      #icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    #- label: "Twitter"
      #icon: "fab fa-fw fa-square-x-twitter"
      # url: "https://twitter.com/"
    #- label: "Facebook"
      #icon: "fab fa-fw fa-square-facebook"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/omae26"
    #- label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

 
# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: github.com/omae26
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/teresia-kemunto
  since: "2026"
